[packages]
    [packages.tar]
        # MUST BE TAR.XZ
        url = "https://ixrepo.pages.dev/arfbones/tar-latest.tar.xz"
        xzname = "tar-latest.tar.xz"
        version = "1.35"
        foldername = "tar-" #SCRIPT ADDS VERSION\
    [packages.session-stay]
        # MUST BE TAR.XZ
        url = "https://ixrepo.pages.dev/arfbones/session-stay-latest.tar.xz"
        xzname = "session-stay-latest.tar.xz"
        version = "1.0"
        foldername = "session-stay-" #SCRIPT ADDS VERSION
    [packages.hsetroot]
        # MUST BE TAR.XZ
        url = "https://ixrepo.pages.dev/arfbones/hsetroot-latest.tar.xz"
        xzname = "hsetroot-latest.tar.xz"
        version = "1.0.2"
        foldername = "hsetroot-" #SCRIPT ADDS VERSION
    [packages.neofetch]
        # MUST BE TAR.XZ
        url = "https://ixrepo.pages.dev/arfbones/neofetch-latest.tar.xz"
        xzname = "neofetch-latest.tar.xz"
        version = "7.1.0"
        foldername = "neofetch-" #SCRIPT ADDS VERSION
    [packages.neofetch]
        # MUST BE TAR.XZ
        url = "https://ixrepo.pages.dev/arfbones/nano-latest.tar.xz"
        xzname = "nano-latest.tar.xz"
        version = "8.3"
        foldername = "nano-" #SCRIPT ADDS VERSION
